#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

### *** CUSTOM ***

#To fix omz: one or more keys are non-bindable
export TERM=xterm-256color


### Alias
# Preventive measures. Prompt for changes
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

#Piping shortcuts
alias -g G="| grep --color=auto"
alias -g L="| less"

alias back='popd'
alias ip='curl ifconfig.me'
alias localip='ipconfig getifaddr en0'
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# alias for cp with progress
# -P implies --partial and --progress, and h humanises the units.
alias ccp="rsync -Ph" 

alias sz="source ~/.zshrc"
### /Alias

# Insert sudo when pressing ctrl+x
insert-sudo () {
  BUFFER="sudo $BUFFER"
}
zle -N insert-sudo
bindkey '^x' insert-sudo

# Added by the Heroku Toolbelt
export PATH=/usr/local/heroku/bin:$PATH

###--- Python
# Python startup file
. ~/.hogar/django_env_functions.sh

export PYTHONSTARTUP=$HOME/.hogar/pythonstartup

export WORKON_HOME=~/.virtualenvs
#mkdir -p $WORKON_HOME
export PIP_VIRTUALENV_BASE=$WORKON_HOME
source /usr/local/bin/virtualenvwrapper.sh
#TO-DO: find a way to apply this on .hogar http://www.doughellmann.com/docs/virtualenvwrapper/tips.html#zsh-prompt

#when cd on a dir with a .venv file, load the venv with the contents of the file
has_virtualenv() {
    if [ -e .venv ]; then
        workon `cat .venv`
    fi
}
venv_cd () {
    builtin cd "$@" && has_virtualenv
}
alias cd="venv_cd"
###--- /Python

export SVN_EDITOR=vim
export GIT_EDITOR=vim
export EDITOR=vim
export VISUAL=vim

###--- alias.sh

extract () {
    if [ -f $1 ] ; then
      case $1 in
        *.tar.bz2)   tar xjf $1     ;;
        *.tar.gz)    tar xzf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xf $1      ;;
        *.tbz2)      tar xjf $1     ;;
        *.tgz)       tar xzf $1     ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

alias upgrade='sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean'

alias avconv='ffmpeg'

#--- Node
export NODE_PATH="/usr/local/lib/node"
export PATH="/usr/local/share/npm/bin:$PATH"
export PATH="$PATH:/usr/local/lib/node_modules"
source $(brew --prefix nvm)/nvm.sh
export PATH="$HOME/.bin:$PATH"


#--- Ruby

## RVM
export rvmsudo_secure_path=0

# recommended by brew doctor
export PATH="/usr/local/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

### Postgres.app
export PATH=/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH
# createuser -s -r postgres
# createdb databasename

# Autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh


# Streaming
alias broadcast="ttyreccast /tmp/outfile.tty"
alias recordtty="reset && ttyrec /tmp/ttycast"
alias train="{ while true; do sl 2>&1; done } | ttycast"

# added by travis gem
[ -f /Users/davidgu/.travis/travis.sh ] && source /Users/davidgu/.travis/travis.sh

# Go
export GOPATH=/Users/davidgu/dev/hackerschool/go
